version: '3.8'

services:
  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: sh -c "npm rebuild bcrypt --build-from-source && npm run start:dev users"
    env_file:
      - ./apps/users/.env
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/postgres?schema=public
    networks:
      - ms_network

  shortener:
    build:
      context: .
      dockerfile: ./apps/shortener/Dockerfile
      target: development
    command: npm run start:dev shortener
    env_file:
      - ./apps/shortener/.env
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/postgres?schema=public
    networks:
      - ms_network

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    depends_on:
      - postgres
      - rabbitmq
      - users
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - ms_network

  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: npm run start:dev gateway
    env_file:
      - ./apps/gateway/.env
    depends_on:
      - postgres
      - rabbitmq
      - users
      - auth
      - shortener
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    networks:
      - ms_network

  rabbitmq:
    image: rabbitmq:3.13.3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - ms_network

  postgres:
    image: postgres:15.4
    container_name: postgres
    volumes:
      - db_users:/db/postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - ms_network

volumes:
  db_users:
  db_shortener:


networks:
  ms_network:
    driver: bridge
